### ISSUE TITLE
BadResponseException

### ISSUE THREAD

**Issue by QuixDK** [PukPukov/bill-payments-java-sdk#3]
Не могу разобраться с проблемой, генерирую счет на оплату, все нормально, а когда пытаюсь узнать статус платежа через 
BillResponse response = client.getBillInfo(billID), получаю exception. Какие могут быть проблемы?

Запись из лога
> 2022-10-19 21:39:00,799 ERROR com.example.WebUFO.service.UFO [UFOtion_Bot Telegram Executor] Payment failed com.qiwi.billpayments.sdk.exception.BadResponseException: ResponseData(body={"siteId":"2x3o3s-00","billId":"554c8628-397a-43fd-bd4d-8b9496f215f1","amount":{"currency":"RUB","value":"530.00"},"status":{"value":"WAITING","changedDateTime":"2022-10-19T17:36:29.534+03:00"},"customFields":{"apiClient":"java_sdk","apiClientVersion":"1.5.1"},"comment":"5559739198","creationDateTime":"2022-10-19T17:36:29.534+03:00","expirationDateTime":"2022-10-19T18:36:06.391+03:00","payUrl":"https://oplata.qiwi.com/form/?invoice_uid=0d007a17-9379-4924-8c39-95de0eadc1c4","recipientPhoneNumber":"*","recipient":{"requisitesType":"PHONE_NUMBER","requisitesValue":"*"}}, httpStatus=200)

**Comment by TABURELTER** [comment]
Если ещё актуально то можно через catch получать ошибку и потом её разбирать: (сорри что скрином![image](https://user-images.githubusercontent.com/60186624/202087929-286ce699-2726-473f-8496-626512712f22.png)

**Comment by QuixDK** [comment]
Да, так и сделал, спасибо.
